# today static data job
static.time_range = 86400
static.page_size = 50
static.keywords = 洛天依,言和,乐正绫,乐正龙牙,徵羽摩柯,墨清弦,星尘,海伊,赤羽,诗岸,苍穹,永夜,心华,中文VOCALOID
static.type_id_white_list = 21,22,24,25,26,27,28,29,30,31,47,59,121,122,126,130,193,216,229,230,231,242,244,265
static.keyword_black_list = 星尘斗士,永夜王,未知原因,星尘细胞法杖,星尘远征军,星尘琪,短剧种草计划,东方永夜抄,斗破苍穹,电子竞技,直播录像,口袋苍穹,来自星尘,永夜之王,永夜大坝

# today dynamic data job
dynamic.group_size = 50
# today dynamic data job - 官方 API 配置
dynamic.executors_size.official = 10
# today dynamic data job - 代理 API 配置（增大 3 倍以弥补延迟）
dynamic.executors_size.proxy = 30

# minute job - 官方 API 配置
minute.num_get_data_threads.official = 4
minute.num_insert_threads.official = 2
# minute job - 代理 API 配置（增大 3 倍以弥补延迟）
minute.num_get_data_threads.proxy = 12
minute.num_insert_threads.proxy = 6
